spring:
  profiles:
    active:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.96.180.164:2222/bottos?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    url: jdbc:mysql://10.104.14.169:2222/bottos?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
#    url: jdbc:mysql://127.0.0.1:3306/bottos?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: Changeme_123
#    below druid config
#最大活跃数
    maxActive: 20
    #初始化数
    initialSize: 1
    #最大连接等待超时时
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
    filters: stat, wall, log4j
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8443
  session:
    timeout: 1000
  context-path: /
  tomcat:
    uri-encoding: utf-8
  ssl:
    key-store: keystore.p12
    key-store-password: Changeme_123
    key-store-type: PKCS12
    key-alias: tomcat
walletPath: "D:"
