spring:
  profiles:
    active:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxxxx/bottos?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: xxxx
    password: xxxx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
walletPath: ""

